name: 'Setup Nuget'
description: 'Goes and downloads latest Nuget.exe as CLI tool and puts it into the path with support for UNIX environments using Mono.'
author: 'Warren Buckley'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'download'
  color: 'purple'
